package com.nexuswavetech.nexusplus.core

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import com.nexuswavetech.nexusplus.navigation.Screen

object FeatureCatalog {

    val allFeatures: List<FeatureItem> = listOf(

        // ── Media & Entertainment ─────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.RADIO_PLAYER,
            name        = "Online Radio",
            description = "Stream thousands of live radio stations worldwide",
            icon        = Icons.Filled.Radio,
            route       = Screen.RadioPlayer.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("radio", "stream", "live", "station", "music", "broadcast", "fm", "am"),
        ),
        FeatureItem(
            id          = FeatureId.AI_IMAGE_GENERATOR,
            name        = "AI Image Generator",
            description = "Generate stunning images from text prompts",
            icon        = Icons.Filled.AutoAwesome,
            route       = Screen.AiImageGenerator.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("ai", "image", "generate", "art", "diffusion", "prompt", "pollinations", "creative"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.IPTV_PLAYER,
            name        = "IPTV / Live TV",
            description = "Stream live Indian TV channels and global M3U playlists",
            icon        = Icons.Filled.LiveTv,
            route       = Screen.IptvPlayer.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("iptv", "tv", "live", "stream", "channel", "m3u", "playlist", "television"),
        ),
        FeatureItem(
            id          = FeatureId.MUSIC_STREAMING,
            name        = "Music Player",
            description = "Stream online music or play local audio files on-device",
            icon        = Icons.Filled.MusicNote,
            route       = Screen.MusicStreaming.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("music", "audio", "player", "stream", "song", "playlist", "mp3"),
        ),
        FeatureItem(
            id          = FeatureId.SMART_IMAGE_EDITOR,
            name        = "Smart Image Editor",
            description = "Crop, rotate, flip and adjust images on-device",
            icon        = Icons.Filled.PhotoFilter,
            route       = Screen.SmartImageEditor.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("image", "editor", "crop", "rotate", "flip", "photo", "adjust", "filter"),
            isNew       = true,
        ),

        // ── Productivity ──────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.PDF_SUITE,
            name        = "PDF Suite",
            description = "Read, create, merge, split and reorder PDF documents",
            icon        = Icons.Filled.PictureAsPdf,
            route       = Screen.PdfSuite.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("pdf", "document", "read", "merge", "split", "viewer", "file"),
        ),
        FeatureItem(
            id          = FeatureId.FILE_MANAGER,
            name        = "File Manager",
            description = "Browse and manage your device files",
            icon        = Icons.Filled.Folder,
            route       = Screen.Stub.route + "/file_manager",
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("file", "folder", "manager", "browse", "storage", "directory"),
        ),
        FeatureItem(
            id          = FeatureId.ALARM_CLOCK,
            name        = "Alarm Clock",
            description = "Smart alarm with custom sounds",
            icon        = Icons.Filled.Alarm,
            route       = Screen.Stub.route + "/alarm",
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("alarm", "clock", "wake", "timer", "schedule"),
        ),
        FeatureItem(
            id          = FeatureId.CLIPBOARD_MANAGER,
            name        = "Clipboard Manager",
            description = "Save, organise, and reuse clipboard history",
            icon        = Icons.Filled.ContentPaste,
            route       = Screen.Stub.route + "/clipboard",
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("clipboard", "copy", "paste", "history", "text"),
        ),
        FeatureItem(
            id          = FeatureId.JSON_FORMATTER,
            name        = "JSON Formatter",
            description = "Format, validate and minify JSON — fully offline",
            icon        = Icons.Filled.DataObject,
            route       = Screen.JsonFormatter.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("json", "format", "validate", "minify", "developer", "api", "prettify"),
        ),
        FeatureItem(
            id          = FeatureId.REGEX_TESTER,
            name        = "Regex Tester",
            description = "Test and debug regular expressions on-device",
            icon        = Icons.Filled.Code,
            route       = Screen.RegexTester.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("regex", "regexp", "pattern", "match", "test", "developer", "string"),
        ),
        FeatureItem(
            id          = FeatureId.DOC_HUB,
            name        = "Doc Hub",
            description = "Quick access storage and organisation for your documents",
            icon        = Icons.Filled.Description,
            route       = Screen.DocHub.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("document", "storage", "organise", "files", "hub", "manage"),
        ),

        // ── Utilities ─────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_TTS,
            name        = "Nexus Speech Engine",
            description = "Multi-language text-to-speech with auto-locale detection",
            icon        = Icons.Filled.RecordVoiceOver,
            route       = Screen.NexusTts.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("tts", "text to speech", "speak", "voice", "read aloud", "language", "nse", "audio"),
        ),
        FeatureItem(
            id          = FeatureId.VOICE_TYPER,
            name        = "Voice Typer",
            description = "Type using your voice via native speech-to-text",
            icon        = Icons.Filled.Mic,
            route       = Screen.VoiceTyper.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("voice", "speech", "type", "dictate", "stt", "microphone", "transcribe"),
        ),
        FeatureItem(
            id          = FeatureId.CURRENCY_CONVERTER,
            name        = "Currency Converter",
            description = "Real-time currency conversion rates",
            icon        = Icons.Filled.CurrencyExchange,
            route       = Screen.Stub.route + "/currency",
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("currency", "convert", "exchange", "forex", "money", "rate", "dollar", "rupee"),
        ),
        FeatureItem(
            id          = FeatureId.UNIT_CONVERTER,
            name        = "Unit Converter",
            description = "Convert length, weight, volume, and more",
            icon        = Icons.Filled.SwapHoriz,
            route       = Screen.Stub.route + "/units",
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("unit", "convert", "length", "weight", "volume", "temperature", "metric"),
        ),
        FeatureItem(
            id          = FeatureId.CALCULATOR_CENTER,
            name        = "Calculator Center",
            description = "Standard math calculator and age calculator in one place",
            icon        = Icons.Filled.Calculate,
            route       = Screen.CalculatorCenter.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("calculator", "math", "compute", "age", "arithmetic", "numbers"),
        ),
        FeatureItem(
            id          = FeatureId.STOPWATCH,
            name        = "Stopwatch",
            description = "Precision stopwatch with lap tracking",
            icon        = Icons.Filled.Timer,
            route       = Screen.Stub.route + "/stopwatch",
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("stopwatch", "timer", "lap", "time", "precision", "countdown"),
        ),
        FeatureItem(
            id          = FeatureId.WORLD_CLOCK,
            name        = "World Clock",
            description = "Track time zones across the globe",
            icon        = Icons.Filled.Language,
            route       = Screen.Stub.route + "/worldclock",
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("clock", "time", "timezone", "world", "global", "zone"),
        ),
        FeatureItem(
            id          = FeatureId.TEXT_TRANSLATOR,
            name        = "Text Translator",
            description = "On-device translation — 50+ languages, no internet needed",
            icon        = Icons.Filled.Translate,
            route       = Screen.TextTranslator.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("translate", "language", "mlkit", "offline", "text", "50+"),
        ),
        FeatureItem(
            id          = FeatureId.MORSE_CODE,
            name        = "Morse Code",
            description = "Encode and decode Morse code with audio playback",
            icon        = Icons.Filled.Keyboard,
            route       = Screen.MorseCode.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("morse", "code", "encode", "decode", "dot", "dash", "audio"),
        ),
        FeatureItem(
            id          = FeatureId.NUMBER_SYSTEM,
            name        = "Number System Converter",
            description = "Binary, Octal, Decimal and Hexadecimal converter",
            icon        = Icons.Filled.Tag,
            route       = Screen.NumberSystem.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("binary", "octal", "decimal", "hex", "hexadecimal", "number", "base", "convert"),
        ),
        FeatureItem(
            id          = FeatureId.WEATHER,
            name        = "Weather",
            description = "Live weather forecasts and alerts",
            icon        = Icons.Filled.WbSunny,
            route       = Screen.Stub.route + "/weather",
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("weather", "forecast", "temperature", "rain", "sun", "alert"),
        ),
        FeatureItem(
            id          = FeatureId.MY_REMINDER,
            name        = "My Reminder",
            description = "Set custom local reminders and notifications",
            icon        = Icons.Filled.NotificationsActive,
            route       = Screen.MyReminder.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("reminder", "notification", "alarm", "schedule", "alert"),
        ),
        FeatureItem(
            id          = FeatureId.FORM_X,
            name        = "Form X",
            description = "Universal reactive form with auto-validation",
            icon        = Icons.Filled.Assignment,
            route       = Screen.FormX.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("form", "input", "validate", "email", "password", "field"),
            isNew       = true,
        ),

        // ── Smart Tools ───────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.QR_GENERATOR,
            name        = "QR Code Generator",
            description = "Generate QR codes for text, URLs and UPI payments",
            icon        = Icons.Filled.QrCode,
            route       = Screen.QrCode.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("qr", "barcode", "generate", "scan", "url", "upi", "payment"),
        ),
        FeatureItem(
            id          = FeatureId.FLASHLIGHT,
            name        = "Flashlight",
            description = "Instant torch control and strobe modes",
            icon        = Icons.Filled.FlashOn,
            route       = Screen.Stub.route + "/flashlight",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("flashlight", "torch", "light", "strobe", "camera"),
        ),
        FeatureItem(
            id          = FeatureId.COMPASS,
            name        = "Compass",
            description = "Magnetic compass with tilt calibration",
            icon        = Icons.Filled.Explore,
            route       = Screen.Stub.route + "/compass",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("compass", "direction", "magnetic", "north", "navigate"),
        ),
        FeatureItem(
            id          = FeatureId.SPEEDOMETER,
            name        = "Speedometer",
            description = "GPS-powered speed tracker",
            icon        = Icons.Filled.Speed,
            route       = Screen.Stub.route + "/speedometer",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("speed", "gps", "velocity", "km", "mph", "track"),
        ),
        FeatureItem(
            id          = FeatureId.VOICE_RECORDER,
            name        = "Voice Recorder",
            description = "High-quality audio recording with waveform",
            icon        = Icons.Filled.GraphicEq,
            route       = Screen.Stub.route + "/recorder",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("record", "voice", "audio", "microphone", "waveform", "memo"),
        ),
        FeatureItem(
            id          = FeatureId.WIFI_ANALYZER,
            name        = "Wi-Fi Analyzer",
            description = "Scan and analyze nearby Wi-Fi networks",
            icon        = Icons.Filled.Wifi,
            route       = Screen.Stub.route + "/wifi",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("wifi", "network", "scan", "signal", "ssid", "analyzer"),
        ),
        FeatureItem(
            id          = FeatureId.BATTERY_MONITOR,
            name        = "Battery Monitor",
            description = "Real-time battery health and usage stats",
            icon        = Icons.Filled.BatteryFull,
            route       = Screen.Stub.route + "/battery",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("battery", "health", "charge", "monitor", "power"),
        ),
        FeatureItem(
            id          = FeatureId.STORAGE_ANALYZER,
            name        = "Storage Analyzer",
            description = "Visualise and free up device storage",
            icon        = Icons.Filled.Storage,
            route       = Screen.Stub.route + "/storage",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("storage", "disk", "space", "clean", "analyze", "memory"),
        ),
        FeatureItem(
            id          = FeatureId.OBJECT_DETECTOR,
            name        = "Object Detector",
            description = "Real-time on-device object detection via camera",
            icon        = Icons.Filled.CenterFocusStrong,
            route       = Screen.ObjectDetector.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("object", "detect", "camera", "ai", "mlkit", "recognition", "real-time"),
        ),
        FeatureItem(
            id          = FeatureId.COLOR_DETECTOR,
            name        = "Colour Detector",
            description = "Identify any colour from camera with name and hex code",
            icon        = Icons.Filled.Colorize,
            route       = Screen.ColorDetector.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("color", "colour", "detect", "hex", "rgb", "camera", "identify"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.BARCODE_GENERATOR,
            name        = "Barcode Generator",
            description = "Generate barcodes in multiple formats",
            icon        = Icons.Filled.QrCodeScanner,
            route       = Screen.Stub.route + "/barcode",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("barcode", "generate", "ean", "upc", "code128", "scan"),
        ),
        FeatureItem(
            id          = FeatureId.TASK_MANAGER,
            name        = "Task Manager",
            description = "Monitor and manage running processes",
            icon        = Icons.Filled.Dashboard,
            route       = Screen.Stub.route + "/tasks",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("task", "process", "manage", "monitor", "cpu", "ram"),
        ),
        FeatureItem(
            id          = FeatureId.SCREEN_RECORDER,
            name        = "Screen Recorder",
            description = "Record your screen with audio overlay",
            icon        = Icons.Filled.ScreenShare,
            route       = Screen.Stub.route + "/screenrecorder",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("screen", "record", "capture", "video", "overlay"),
        ),

        // ── Security & Privacy ────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.BIOMETRIC_VAULT,
            name        = "Biometric Vault",
            description = "Securely store passwords, notes, cards and documents — biometric protected",
            icon        = Icons.Filled.Fingerprint,
            route       = Screen.BiometricVault.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("vault", "biometric", "fingerprint", "secure", "password", "notes", "private"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.ENCRYPTER_DECRYPTER,
            name        = "Encrypter and Decrypter",
            description = "AES-256 encrypt/decrypt text, images and files on-device",
            icon        = Icons.Filled.EnhancedEncryption,
            route       = Screen.EncrypterDecrypter.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("encrypt", "decrypt", "aes", "256", "cipher", "secure", "file", "text"),
        ),
        FeatureItem(
            id          = FeatureId.HASH_GENERATOR,
            name        = "Hash Generator",
            description = "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
            icon        = Icons.Filled.Tag,
            route       = Screen.HashGenerator.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("hash", "md5", "sha", "sha256", "sha512", "checksum", "digest"),
        ),
        FeatureItem(
            id          = FeatureId.PASSWORD_GENERATOR,
            name        = "Password Generator",
            description = "Create strong, customisable passwords instantly",
            icon        = Icons.Filled.Key,
            route       = Screen.PasswordGenerator.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("password", "generate", "strong", "random", "secure", "credentials"),
        ),
        FeatureItem(
            id          = FeatureId.BASE64_TOOL,
            name        = "Base64 Tool",
            description = "Encode and decode Base64 strings on-device",
            icon        = Icons.Filled.SwapVert,
            route       = Screen.Base64Tool.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("base64", "encode", "decode", "string", "data"),
        ),
        FeatureItem(
            id          = FeatureId.ENCRYPTED_NOTES,
            name        = "Encrypted Notes",
            description = "Private, AES-256 encrypted personal notes",
            icon        = Icons.Filled.Lock,
            route       = Screen.Stub.route + "/notes",
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("notes", "encrypted", "private", "secure", "aes", "diary"),
        ),
        FeatureItem(
            id          = FeatureId.APP_LOCKER,
            name        = "App Locker",
            description = "Protect apps with biometric authentication",
            icon        = Icons.Filled.Security,
            route       = Screen.Stub.route + "/applocker",
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("locker", "app", "biometric", "protect", "lock", "fingerprint"),
        ),
        FeatureItem(
            id          = FeatureId.CONTACT_BACKUP,
            name        = "Contact Backup",
            description = "Backup and restore your contacts securely",
            icon        = Icons.Filled.Contacts,
            route       = Screen.Stub.route + "/contacts",
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("contact", "backup", "restore", "sync", "vcf", "secure"),
        ),
    )

    /** All features grouped by [FeatureHub]. */
    val byHub: Map<FeatureHub, List<FeatureItem>> by lazy {
        FeatureHub.entries.associateWith { hub ->
            allFeatures.filter { it.category.toHub() == hub }
        }
    }

    /** Features belonging to a specific hub. */
    fun forHub(hub: FeatureHub): List<FeatureItem> = byHub[hub] ?: emptyList()
}
