uploads = []
generated = []

[[outputs]]
id = "smco-W4-xcSW2bwCK0yaB"
uri = "file://NexusPlus/nexusplus-signing-keys.zip"
type = "unspecified"
title = "nexusplus-signing-keys.zip — Android Keystore + Credentials"

[[outputs]]
id = "yF42Ym7nXPyAWVTcoe0FF"
uri = "file://nexusplus-keystore-package.zip"
type = "unspecified"
title = "NexusPlus Keystore Package"
