package com.nexuswavetech.nexusplus.core

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.Assignment
import androidx.compose.material.icons.automirrored.filled.ScreenShare
import androidx.compose.material.icons.filled.*
import com.nexuswavetech.nexusplus.navigation.Screen

object FeatureCatalog {

    val allFeatures: List<FeatureItem> = listOf(

        // ── Media & Entertainment ─────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.AI_IMAGE_GENERATOR,
            name        = "AI Image Generator",
            description = "Generate stunning images from text prompts",
            icon        = Icons.Filled.AutoAwesome,
            route       = Screen.AiImageGenerator.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("ai", "image", "generate", "art", "diffusion", "prompt", "pollinations", "creative"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.MUSIC_STREAMING,
            name        = "Nexus Media Player",
            description = "Stream online music or play local audio & video files on-device",
            icon        = Icons.Filled.PlayCircleFilled,
            route       = Screen.MusicStreaming.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("music", "audio", "video", "player", "stream", "song", "playlist", "mp3", "media"),
        ),
        FeatureItem(
            id          = FeatureId.NEXUS_IMAGE_VIEWER,
            name        = "Nexus Image Viewer",
            description = "View, zoom, rotate and share images with pinch-to-zoom support",
            icon        = Icons.Filled.Photo,
            route       = Screen.NexusImageViewer.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("image", "viewer", "photo", "gallery", "zoom", "rotate", "jpg", "png"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.SMART_IMAGE_EDITOR,
            name        = "Smart Image Editor",
            description = "Crop, rotate, flip and adjust images on-device",
            icon        = Icons.Filled.PhotoFilter,
            route       = Screen.SmartImageEditor.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("image", "editor", "crop", "rotate", "flip", "photo", "adjust", "filter"),
            isNew       = true,
        ),

        // ── Productivity ──────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.PDF_SUITE,
            name        = "PDF Suite",
            description = "Read, create, merge, split and reorder PDF documents",
            icon        = Icons.Filled.PictureAsPdf,
            route       = Screen.PdfSuite.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("pdf", "document", "read", "merge", "split", "viewer", "file"),
        ),
        FeatureItem(
            id          = FeatureId.FILE_MANAGER,
            name        = "File Manager",
            description = "Browse and manage your device files and folders",
            icon        = Icons.Filled.Folder,
            route       = Screen.FileManager.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("file", "folder", "manager", "browse", "storage", "directory"),
        ),
        FeatureItem(
            id          = FeatureId.ALARM_CLOCK,
            name        = "Alarm Clock",
            description = "Precise alarms with repeat scheduling and custom labels",
            icon        = Icons.Filled.Alarm,
            route       = Screen.AlarmClock.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("alarm", "clock", "wake", "timer", "schedule"),
        ),
        FeatureItem(
            id          = FeatureId.CLIPBOARD_MANAGER,
            name        = "Clipboard Manager",
            description = "Save, organise, and reuse clipboard history",
            icon        = Icons.Filled.ContentPaste,
            route       = Screen.ClipboardManager.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("clipboard", "copy", "paste", "history", "text"),
        ),
        FeatureItem(
            id          = FeatureId.JSON_FORMATTER,
            name        = "JSON Formatter",
            description = "Format, validate and minify JSON — fully offline",
            icon        = Icons.Filled.DataObject,
            route       = Screen.JsonFormatter.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("json", "format", "validate", "minify", "developer", "api", "prettify"),
        ),
        FeatureItem(
            id          = FeatureId.REGEX_TESTER,
            name        = "Regex Tester",
            description = "Test and debug regular expressions on-device",
            icon        = Icons.Filled.Code,
            route       = Screen.RegexTester.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("regex", "regexp", "pattern", "match", "test", "developer", "string"),
        ),
        FeatureItem(
            id          = FeatureId.DOC_HUB,
            name        = "Document Organizer",
            description = "Organise, access and manage your documents in one place",
            icon        = Icons.Filled.Description,
            route       = Screen.DocHub.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("document", "storage", "organise", "files", "hub", "manage"),
        ),
        FeatureItem(
            id          = FeatureId.NEXUS_DOC_READER,
            name        = "Nexus Document Reader",
            description = "Read PDF, TXT, DOC, DOCX and more with built-in TTS support",
            icon        = Icons.Filled.MenuBook,
            route       = Screen.NexusDocReader.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("document", "reader", "pdf", "doc", "txt", "read", "tts", "nexus"),
            isNew       = true,
        ),

        // ── Utilities ─────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_TTS,
            name        = "Nexus Auto Speech Engine",
            description = "Multi-language text-to-speech with auto-locale detection",
            icon        = Icons.Filled.RecordVoiceOver,
            route       = Screen.NexusTts.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("tts", "text to speech", "speak", "voice", "read aloud", "language", "nse", "audio", "nexus auto speech engine", "nase"),
        ),
        FeatureItem(
            id          = FeatureId.VOICE_TYPER,
            name        = "Voice Typer",
            description = "Type using your voice via native speech-to-text",
            icon        = Icons.Filled.Mic,
            route       = Screen.VoiceTyper.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("voice", "speech", "type", "dictate", "stt", "microphone", "transcribe"),
        ),
        FeatureItem(
            id          = FeatureId.CURRENCY_CONVERTER,
            name        = "Currency Converter",
            description = "30 currency offline reference converter with live rate hints",
            icon        = Icons.Filled.CurrencyExchange,
            route       = Screen.CurrencyConverter.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("currency", "convert", "exchange", "forex", "money", "rate", "dollar", "rupee"),
        ),
        FeatureItem(
            id          = FeatureId.UNIT_CONVERTER,
            name        = "Unit Converter",
            description = "Convert length, weight, volume, area, speed, data and more",
            icon        = Icons.Filled.SwapHoriz,
            route       = Screen.UnitConverter.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("unit", "convert", "length", "weight", "volume", "temperature", "metric"),
        ),
        FeatureItem(
            id          = FeatureId.CALCULATOR_CENTER,
            name        = "Calculator Center",
            description = "Standard math calculator and age calculator in one place",
            icon        = Icons.Filled.Calculate,
            route       = Screen.CalculatorCenter.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("calculator", "math", "compute", "age", "arithmetic", "numbers"),
        ),
        FeatureItem(
            id          = FeatureId.STOPWATCH,
            name        = "Stopwatch",
            description = "Precision stopwatch with centisecond accuracy and lap tracking",
            icon        = Icons.Filled.Timer,
            route       = Screen.Stopwatch.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("stopwatch", "timer", "lap", "time", "precision", "countdown"),
        ),
        FeatureItem(
            id          = FeatureId.WORLD_CLOCK,
            name        = "World Clock",
            description = "Track multiple time zones across the globe simultaneously",
            icon        = Icons.Filled.Language,
            route       = Screen.WorldClock.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("clock", "time", "timezone", "world", "global", "zone"),
        ),
        FeatureItem(
            id          = FeatureId.TEXT_TRANSLATOR,
            name        = "Text Translator",
            description = "On-device translation — 50+ languages, no internet needed",
            icon        = Icons.Filled.Translate,
            route       = Screen.TextTranslator.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("translate", "language", "mlkit", "offline", "text", "50+"),
        ),
        FeatureItem(
            id          = FeatureId.MORSE_CODE,
            name        = "Morse Code",
            description = "Encode and decode Morse code with audio playback",
            icon        = Icons.Filled.Keyboard,
            route       = Screen.MorseCode.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("morse", "code", "encode", "decode", "dot", "dash", "audio"),
        ),
        FeatureItem(
            id          = FeatureId.NUMBER_SYSTEM,
            name        = "Number System Converter",
            description = "Binary, Octal, Decimal and Hexadecimal converter",
            icon        = Icons.Filled.Tag,
            route       = Screen.NumberSystem.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("binary", "octal", "decimal", "hex", "hexadecimal", "number", "base", "convert"),
        ),
        FeatureItem(
            id          = FeatureId.WEATHER,
            name        = "Weather",
            description = "Live weather forecasts and alerts",
            icon        = Icons.Filled.WbSunny,
            route       = Screen.Weather.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("weather", "forecast", "temperature", "rain", "sun", "alert"),
        ),
        FeatureItem(
            id          = FeatureId.MY_REMINDER,
            name        = "My Reminder",
            description = "Set custom local reminders and notifications",
            icon        = Icons.Filled.NotificationsActive,
            route       = Screen.MyReminder.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("reminder", "notification", "alarm", "schedule", "alert"),
        ),
        // ── AI ────────────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.AIRA_AI,
            name        = "Aira AI",
            description = "Chat with Aira — your intelligent AI assistant",
            icon        = Icons.Filled.AutoAwesome,
            route       = Screen.AiraAi.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("ai", "chat", "aira", "assistant", "gpt", "intelligence", "pollinations", "nexus"),
            isNew       = true,
        ),

        // ── Smart Tools ───────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.QR_GENERATOR,
            name        = "QR Code Generator",
            description = "Generate QR codes for text, URLs and UPI payments",
            icon        = Icons.Filled.QrCode,
            route       = Screen.QrCode.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("qr", "barcode", "generate", "scan", "url", "upi", "payment"),
        ),
        FeatureItem(
            id          = FeatureId.FLASHLIGHT,
            name        = "Flashlight",
            description = "Instant torch control and strobe mode",
            icon        = Icons.Filled.FlashOn,
            route       = Screen.Flashlight.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("flashlight", "torch", "light", "strobe", "camera"),
        ),
        FeatureItem(
            id          = FeatureId.COMPASS,
            name        = "Compass",
            description = "Rotation-vector compass with tilt and azimuth data",
            icon        = Icons.Filled.Explore,
            route       = Screen.Compass.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("compass", "direction", "magnetic", "north", "navigate"),
        ),
        FeatureItem(
            id          = FeatureId.SPEEDOMETER,
            name        = "Speedometer",
            description = "GPS-powered speed tracker",
            icon        = Icons.Filled.Speed,
            route       = Screen.Speedometer.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("speed", "gps", "velocity", "km", "mph", "track"),
        ),
        FeatureItem(
            id          = FeatureId.VOICE_RECORDER,
            name        = "Voice Recorder",
            description = "High-quality AAC audio recording with session history",
            icon        = Icons.Filled.GraphicEq,
            route       = Screen.VoiceRecorder.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("record", "voice", "audio", "microphone", "waveform", "memo"),
        ),
        FeatureItem(
            id          = FeatureId.WIFI_ANALYZER,
            name        = "Wi-Fi Analyzer",
            description = "Scan and analyse nearby Wi-Fi networks with signal strength",
            icon        = Icons.Filled.Wifi,
            route       = Screen.WifiAnalyzer.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("wifi", "network", "scan", "signal", "ssid", "analyzer"),
        ),
        FeatureItem(
            id          = FeatureId.BATTERY_MONITOR,
            name        = "Battery Monitor",
            description = "Real-time battery health, temperature, voltage and charge stats",
            icon        = Icons.Filled.BatteryFull,
            route       = Screen.BatteryMonitor.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("battery", "health", "charge", "monitor", "power"),
        ),
        FeatureItem(
            id          = FeatureId.STORAGE_ANALYZER,
            name        = "Storage Analyzer",
            description = "Visualise internal and external storage usage by category",
            icon        = Icons.Filled.Storage,
            route       = Screen.StorageAnalyzer.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("storage", "disk", "space", "clean", "analyze", "memory"),
        ),
        FeatureItem(
            id          = FeatureId.OBJECT_DETECTOR,
            name        = "Object Detector",
            description = "Real-time on-device object detection via camera",
            icon        = Icons.Filled.CenterFocusStrong,
            route       = Screen.ObjectDetector.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("object", "detect", "camera", "ai", "mlkit", "recognition", "real-time"),
        ),
        FeatureItem(
            id          = FeatureId.COLOR_DETECTOR,
            name        = "Colour Detector",
            description = "Identify any colour from camera with name and hex code",
            icon        = Icons.Filled.Colorize,
            route       = Screen.ColorDetector.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("color", "colour", "detect", "hex", "rgb", "camera", "identify"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.BARCODE_GENERATOR,
            name        = "Barcode Generator",
            description = "Generate CODE 128, EAN, UPC, Data Matrix, PDF 417 barcodes",
            icon        = Icons.Filled.QrCodeScanner,
            route       = Screen.BarcodeGenerator.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("barcode", "generate", "ean", "upc", "code128", "scan"),
        ),
        FeatureItem(
            id          = FeatureId.TASK_MANAGER,
            name        = "Task Manager",
            description = "Monitor and manage running processes",
            icon        = Icons.Filled.Dashboard,
            route       = Screen.TaskManager.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("task", "process", "manage", "monitor", "cpu", "ram"),
        ),
        FeatureItem(
            id          = FeatureId.SCREEN_RECORDER,
            name        = "Screen Recorder",
            description = "Record your screen with audio overlay",
            icon        = Icons.AutoMirrored.Filled.ScreenShare,
            route       = Screen.Stub.route + "/screenrecorder",
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("screen", "record", "capture", "video", "overlay"),
        ),

        // ── Security & Privacy ────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.EMERGENCY_GUARDIAN,
            name        = "Emergency Guardian",
            description = "Shake-triggered SOS: auto-sends GPS location via SMS and calls contacts",
            icon        = Icons.Filled.Shield,
            route       = Screen.EmergencyGuardian.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("emergency", "sos", "guardian", "shake", "sms", "call", "gps", "safety", "alert", "distress"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.BIOMETRIC_VAULT,
            name        = "Biometric Vault",
            description = "AES-256-GCM encrypted vault for passwords, cards & documents",
            icon        = Icons.Filled.Fingerprint,
            route       = Screen.BiometricVault.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("vault", "biometric", "fingerprint", "secure", "password", "notes", "private"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.ENCRYPTER_DECRYPTER,
            name        = "Encrypter and Decrypter",
            description = "AES-256 encrypt/decrypt text, images and files on-device",
            icon        = Icons.Filled.EnhancedEncryption,
            route       = Screen.EncrypterDecrypter.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("encrypt", "decrypt", "aes", "256", "cipher", "secure", "file", "text"),
        ),
        FeatureItem(
            id          = FeatureId.HASH_GENERATOR,
            name        = "Hash Generator",
            description = "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
            icon        = Icons.Filled.Tag,
            route       = Screen.HashGenerator.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("hash", "md5", "sha", "sha256", "sha512", "checksum", "digest"),
        ),
        FeatureItem(
            id          = FeatureId.PASSWORD_GENERATOR,
            name        = "Password Generator",
            description = "Create strong, customisable passwords instantly",
            icon        = Icons.Filled.Key,
            route       = Screen.PasswordGenerator.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("password", "generate", "strong", "random", "secure", "credentials"),
        ),
        FeatureItem(
            id          = FeatureId.BASE64_TOOL,
            name        = "Base64 Tool",
            description = "Encode and decode Base64 strings on-device",
            icon        = Icons.Filled.SwapVert,
            route       = Screen.Base64Tool.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("base64", "encode", "decode", "string", "data"),
        ),
        FeatureItem(
            id          = FeatureId.ENCRYPTED_NOTES,
            name        = "Encrypted Notes",
            description = "Private, AES-256 encrypted personal notes",
            icon        = Icons.Filled.Lock,
            route       = Screen.EncryptedNotes.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("notes", "encrypted", "private", "secure", "aes", "diary"),
        ),
        FeatureItem(
            id          = FeatureId.APP_LOCKER,
            name        = "App Locker",
            description = "Protect apps with biometric authentication",
            icon        = Icons.Filled.Security,
            route       = Screen.Stub.route + "/applocker",
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("locker", "app", "biometric", "protect", "lock", "fingerprint"),
        ),
        FeatureItem(
            id          = FeatureId.CONTACT_BACKUP,
            name        = "Contact Backup",
            description = "Backup and restore your contacts securely",
            icon        = Icons.Filled.Contacts,
            route       = Screen.Stub.route + "/contacts",
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("contact", "backup", "restore", "sync", "vcf", "secure"),
        ),

        // ── Health & Wellbeing ────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_HEALTH_VAULT,
            name        = "Health Vault",
            description = "Secure offline health records — vitals, medications, appointments",
            icon        = Icons.Filled.HealthAndSafety,
            route       = Screen.NexusHealthVault.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("health", "vitals", "medical", "medications", "appointments", "vault", "records"),
            isNew       = true,
        ),

        // ── New features ──────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.TOTP_AUTHENTICATOR,
            name        = "TOTP Authenticator",
            description = "Generate 2FA one-time passwords (Google Authenticator compatible)",
            icon        = Icons.Filled.Key,
            route       = Screen.TotpAuthenticator.route,
            category    = FeatureCategory.SECURITY,
            keywords    = listOf("totp", "2fa", "otp", "authenticator", "mfa", "google", "one-time"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.NETWORK_SPEED_TEST,
            name        = "Speed Test",
            description = "Test internet download, upload speed and ping latency",
            icon        = Icons.Filled.Speed,
            route       = Screen.NetworkSpeedTest.route,
            category    = FeatureCategory.TOOLS,
            keywords    = listOf("speed", "internet", "download", "upload", "ping", "mbps", "network", "wifi"),
            isNew       = true,
        ),

        // ── Stage 4 ───────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_DIALER,
            name        = "Nexus Dialer",
            description = "Full-featured phone dialer with contacts browser and quick-dial",
            icon        = Icons.Filled.Call,
            route       = Screen.NexusDialer.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("dialer", "phone", "call", "contacts", "dial", "number", "telephone"),
            isNew       = true,
        ),
        FeatureItem(
            id          = FeatureId.TEXT_ANALYZER,
            name        = "Text Analyzer",
            description = "Instant word count, reading time, top words and character stats",
            icon        = Icons.Filled.Analytics,
            route       = Screen.TextAnalyzer.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("text", "analyze", "word", "count", "reading", "time", "stats", "characters"),
            isNew       = true,
        ),

        // ── Stage 5 ─────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.URL_SHORTENER,
            name        = "URL Shortener",
            description = "Shorten long URLs using TinyURL, is.gd or v.gd — with copy & open",
            icon        = Icons.Filled.Link,
            route       = Screen.UrlShortener.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("url", "shortener", "link", "shorten", "tinyurl", "isgd", "share", "web"),
            isNew       = true,
        ),

        // ── Nexus OTT ─────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_OTT,
            name        = "Nexus OTT",
            description = "Stream public-domain movies, documentaries and classic TV — legally free",
            icon        = Icons.Filled.VideoLibrary,
            route       = Screen.NexusOtt.route,
            category    = FeatureCategory.MEDIA,
            keywords    = listOf("ott", "movie", "stream", "video", "film", "documentary", "classic", "public domain", "archive", "free", "watch"),
            isNew       = true,
        ),

        // ── Nexus Games Hub ───────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEXUS_GAMES,
            name        = "Nexus Games",
            description = "6 offline HTML5 mini-games: Snake, 2048, Tic-Tac-Toe, Memory, Breakout & Minesweeper",
            icon        = Icons.Filled.SportsEsports,
            route       = Screen.NexusGames.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("game", "games", "snake", "2048", "tictactoe", "memory", "breakout", "minesweeper", "play", "fun", "offline"),
            isNew       = true,
        ),

        // ── News & ePapers ────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.NEWS,
            name        = "News & ePapers",
            description = "Read top headlines and ePapers from public RSS and news feeds",
            icon        = Icons.Filled.Newspaper,
            route       = Screen.News.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("news", "headline", "rss", "feed", "newspaper", "epaper", "read", "article", "current affairs"),
            isNew       = true,
        ),

        // ── Science ──────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.SCIENCE,
            name        = "Science Explorer",
            description = "Explore science facts, discoveries and articles from open sources",
            icon        = Icons.Filled.Science,
            route       = Screen.Science.route,
            category    = FeatureCategory.UTILITIES,
            keywords    = listOf("science", "facts", "discover", "research", "physics", "biology", "chemistry", "space", "article"),
            isNew       = true,
        ),

        // ── Finance ───────────────────────────────────────────────────────────
        FeatureItem(
            id          = FeatureId.EXPENSE_TRACKER,
            name        = "Nexus Expense Tracker",
            description = "Track income and expenses with categories, summaries and local storage",
            icon        = Icons.Filled.AccountBalanceWallet,
            route       = Screen.ExpenseTracker.route,
            category    = FeatureCategory.PRODUCTIVITY,
            keywords    = listOf("expense", "budget", "finance", "money", "income", "spend", "tracker", "wallet", "balance"),
            isNew       = true,
        ),

    )

    /** All features grouped by [FeatureHub]. */
    val byHub: Map<FeatureHub, List<FeatureItem>> by lazy {
        FeatureHub.entries.associateWith { hub ->
            allFeatures.filter { it.category.toHub() == hub }
        }
    }

    /** Features belonging to a specific hub. */
    fun forHub(hub: FeatureHub): List<FeatureItem> = byHub[hub] ?: emptyList()

    /** Register all features into the dynamic [FeatureRegistry] (Priority 4). */
    fun registerAllFeatures() {
        com.nexuswavetech.nexusplus.core.registry.FeatureRegistry.registerAll(allFeatures)
    }

    /** Feature count derived from [FeatureRegistry] — no hardcoding. */
    val totalCount: Int get() = allFeatures.size
}
